### ISSUE TITLE
Depreciate `Libtask.consume` in favour of `Base.iterate`?

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#115]
For example, we can replace 

```julia
using Libtask

function f()
  t = 0
  for _ in 1:10
    produce(t)
    t = 1 + t
  end
end

t = CTask(f)

while (x=consume(t)) !== nothing
  println(x)
end
```

with 

```julia


for i in CTask(f)
  println(i)
end
```

So, we can remove the `Libtask.consume` functions from `Libtask`'s public API. 

Furthermore, with the tape-based `CTask` implementation, we have complete control over executing a task's function. It allows us to also remove the `Libtask.produce` function by inspecting the `Instruction` type. That is 

```julia
function (tf::TapedFunction)(args...; F=typeof(observe), callback=nothing)
    # run the raw tape
    if(tf.counter <= 1 && length(args) > 0)
        input = map(Box{Any}, args)
        tf.tape[1].input = input
    end

    while true
        ins = tf[tf.counter]
        ins()
        (ins.func isa F) && callback() 
        isa(ins, ReturnInstruction) && break
    end
    return result(tf)
end
```

This new `TapedFunction` callback implementation removes the requirement for calling `Libtask.produce` from `tf.func` (see e.g. [here](https://github.com/TuringLang/Turing.jl/pull/1770/files#diff-8d16dd13c316055e55f300cd24294bb2f73f46cbcb5a481f8936ff56939da7ceR366))

**Comment by KDr2** [comment]
> It allows us to also remove the Libtask.produce function by inspecting the Instruction type.

But then how do we produce values in functions like `observe` without `Libtask.produce`?
