### ISSUE TITLE
Replace `IRTools` with `CodeInfoTools` 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#117]

**Comment by devmotion** [comment]
Is it better? I am not familiar with the differences (according to the README it is based closely on IRTools) but it seems it is developed less actively and has fewer contributors (and is only used by Mixtape.jl but no other package yet).

**Comment by yebai** [comment]
`CodeInfoTool` is based on the new compiler data structures and APIs in Julia 1.7. Since `CodeInfoTools` is just a small set of utilities for making Julia's compiler API more friendly, it should be more stable than `IRTools` in general - that's probably why `CodeInfoTools` does not need any changes for a long time. In the worst case, it should not be hard to switch using Julia's native compiler API from `CodeInfoTools`. However, it is slightly less user-friendly.

**Comment by femtomc** [comment]
> `CodeInfoTool` is based on the new compiler data structures (i.e. `CodeInfo`) and APIs in Julia 1.7. Since `CodeInfoTools` is just a small set of utilities for making Julia's compiler API more friendly, it should be more stable than `IRTools` in general - that's probably why `CodeInfoTools` does not need any changes for a long time. In the worst case, it should not be hard to switch to using Julia's native compiler API from `CodeInfoTools`. However, Julia's compiler API is slightly less user-friendly in its current form.

This is the right idea. CodeInfoTools should be thought of as an intermediate step before better APIs are actually part of Core.
