### ISSUE TITLE
Cache key in tapedfunction

### ISSUE THREAD

**Issue by FredericWantiez** [TuringLang/Libtask.jl#158]
Was looking at
https://github.com/TuringLang/Libtask.jl/blob/5ec9f2bafcb8f2716741efb2845efda5a465b3fd/src/tapedfunction.jl#L65

Shouldn't it be something like this instead ?
```julia
cache_key = (f, deepcopy_types, args_type...) 
```
Otherwise this is giving counterintuitive results:
```julia
struct Dummy 
    a::Array
end

function f(d::Dummy)
    produce(d.a)
end

d = Dummy([1])
t = TapedTask(f, d) # No Dummy in deepcopy_types
t2 = TapedTask(f, d; deepcopy_types=Dummy) # Dummy won't be part of the deepcopy_types
```

**Comment by FredericWantiez** [comment]
It's a weird edge case I agree

**Comment by yebai** [comment]
Thanks, @FredericWantiez. That's indeed a subtle bug - would you like to submit a PR?
