### ISSUE TITLE
Works only on 1.0

### ISSUE THREAD

**Issue by Vaibhavdixit02** [TuringLang/Libtask.jl#4]
Hey I was curious if there was some specific reason as to why the Julia requirement for this package was fixed to 1.0 and not 0.7?

**Comment by yebai** [comment]
`Libtask` should work on both Julia 0.7 and 1.0. I've tested it on my local machine. 

However, there is an issue with BinaryProvider on JuliaCIBot, which prevents us from using Julia 0.7. See

https://github.com/JuliaLang/METADATA.jl/pull/17764#issuecomment-419377009

**Comment by Vaibhavdixit02** [comment]
Okay thanks for the clarification.
