### ISSUE TITLE
Load error on Windows and Julia 1.2

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Libtask.jl#43]
Hi,

I am getting the following load error with Julia 1.2 and Windows:
```julia
(v1.2) pkg> build Libtask
  Building Libtask → `C:\Users\user\.julia\packages\Libtask\RjRkK\deps\build.log`
┌ Error: Error building `Libtask`:
│ fatal: not a git repository (or any of the parent directories): .git
│ ┌ Error: Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
│ └ @ Base download.jl:43
│ ERROR: LoadError: failed process: Process(`git -C 'C:\Users\user\.julia\packages\Libtask\RjRkK' tag`, ProcessExited(128)) [128]
│
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:813 [inlined]
│  [2] (::getfield(Base, Symbol("##533#534")){Base.Process})() at .\process.jl:621
│  [3] iterate(::Base.EachLine{Base.PipeEndpoint}, ::Nothing) at .\io.jl:893 (repeats 2 times)
│  [4] _collect(::UnitRange{Int64}, ::Base.EachLine{Base.PipeEndpoint}, ::Base.HasEltype, ::Base.SizeUnknown) at .\array.jl:555
│  [5] collect at .\array.jl:544 [inlined]
│  [6] #readlines#290 at .\io.jl:427 [inlined]
│  [7] readlines at .\io.jl:427 [inlined]
│  [8] find_prev_tag(::String) at C:\Users\user\.julia\packages\Libtask\RjRkK\deps\build.jl:3
│  [9] include_build_script(::SubString{String}, ::Bool) at C:\Users\user\.julia\packages\Libtask\RjRkK\deps\build.jl:42
│  [10] top-level scope at C:\Users\user\.julia\packages\Libtask\RjRkK\deps\build.jl:62
│  [11] include at .\boot.jl:328 [inlined]
│  [12] include_relative(::Module, ::String) at .\loading.jl:1094
│  [13] include(::Module, ::String) at .\Base.jl:31
│  [14] include(::String) at .\client.jl:431
│  [15] top-level scope at none:5
│ in expression starting at C:\Users\user\.julia\packages\Libtask\RjRkK\deps\build.jl:62
└ @ Pkg.Operations C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.2\Pkg\src\backwards_compatible_isolation.jl:647

julia> versioninfo()
Julia Version 1.2.0
Commit c6da87ff4b (2019-08-20 00:03 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```

**Comment by KDr2** [comment]
Hi @mohamed82008, the build script will read `Project.toml` under the Libtask package dir to obtain the current version, then download the corresponding dynamic library.

If this process fails (no `Project.toml` found, or no version setting in that file), it will assume the package dir a git repository, and use a git command to find the latest tag the use it as the version number.

According to the error info you posted, it seems that it failed to find the current version from the `Project.toml` file, and the package dir is not a git repo either.

Generally, there must be a `Project.toml` file under the package dir, this is mine:

```sh
[000]zhuoq@ZHUOQL-XPS:/c/Users/zhuoq/.julia/packages/Libtask/RjRkK$ pwd
/c/Users/zhuoq/.julia/packages/Libtask/RjRkK
[000]zhuoq@ZHUOQL-XPS:/c/Users/zhuoq/.julia/packages/Libtask/RjRkK$ ls -a
.  ..  .gitignore  .travis.yml  appveyor.yml  deps  LICENSE  Project.toml  README.md  src  test
[000]zhuoq@ZHUOQL-XPS:/c/Users/zhuoq/.julia/packages/Libtask/RjRkK$ grep version Project.toml
version = "0.3.1"
[000]zhuoq@ZHUOQL-XPS:/c/Users/zhuoq/.julia/packages/Libtask/RjRkK$
```

Do you have this file in the package dir? I didn't get an idea of why this file is missing for now, will gid deeper.

**Comment by mohamed82008** [comment]
The file is there:
```
user@DESKTOP-32VUB91 MINGW64 ~/.julia/packages/Libtask/RjRkK
$ ls
appveyor.yml  deps/  LICENSE  Project.toml  README.md  src/  test/

user@DESKTOP-32VUB91 MINGW64 ~/.julia/packages/Libtask/RjRkK
$ grep version Project.toml
version = "0.3.1"
```

**Comment by KDr2** [comment]
Oh, I know, it's an error while downloading files from github using CURL.

[Here](https://github.com/TuringLang/Libtask.jl/blob/master/deps/build.jl#L40) we try to download https://github.com/TuringLang/Libtask.jl/releases/download/v0.3.1/build_LibtaskDylib.v0.3.1.jl, then an error occurred:

```
Error: Download failed: curl: (35) schannel: next InitializeSecurityContext failed: Unknown error (0x80092012) - The revocation function was unable to check revocation for the certificate.
```   
I did some search on the internet, it seems that you are using a proxy? That may interfere with the CULR's SSL connection.

see: https://curl.haxx.se/mail/lib-2016-03/0202.html

**Comment by mohamed82008** [comment]
I am not using a proxy no.

**Comment by KDr2** [comment]
Hmm, could you:
1. in the Julia REPL, type ";" to enter the shell mode
2. run the command `curl -L https://github.com/TuringLang/Libtask.jl/releases/download/v0.3.1/build_LibtaskDylib.v0.3.1.jl`

to check if you can download the script successfully? 
If there is no error, please try to build `Libtask` again.

**Comment by mohamed82008** [comment]
Ok it was unsuccessful because the antivirus thought the server was suspicious. I added 2 urls to exclusions and it worked. Thank you. Do you know why this is an issue in Julia 1.2 but 1.1?

**Comment by KDr2** [comment]
I am not sure of that. I run `; curl --version` under Julia 1.1 and 1.2 on my windows box, it shows the same version of CURL was used (and I didn't get the build error on both Julia versions either).

I think all Julia installations use the same CURL in common case, so I have no idea of the difference. Maybe the antivirus treats them differently?

**Comment by mohamed82008** [comment]
Oh well, I am getting the same version too. I will close the issue for now. If someone else reports the same issue, we can look into it again. Thanks for your help.
