### ISSUE TITLE
Replacing `TArray` with compiler-based copy-on-write

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#44]
The `TArray`-family data structure in `Libtask` provides a copy-on-write mechanism for heap-allocated data structures. This is helpful when we want to decouple heap-allocated data structures after tasks are forked, i.e. each task will get an independent copy of heap-allocated variables, and mutating these variables from one task won't affect other tasks. The current implementation requires the user to use `TArray`-like constructors instead of `Array`s. This is inconvenient and sometimes confusing. It should be possible to completely replace the functionality of `TArray` by using a compiler-based implementation. 

The basic idea is to detect `yield` points in static single assignment (SSA) form of functions, then use an SSA manipulation tool (e.g. IRTools) to explicit insert statements that detect task-copying and deep copy variables that are mutated after the task-copying point.

**Comment by KDr2** [comment]
Ways we've tried:
- https://github.com/TuringLang/Libtask.jl/pull/63
- https://github.com/TuringLang/Libtask.jl/pull/79

**Comment by yebai** [comment]
Closed as this does not work well #63 #79
