### ISSUE TITLE
Release Libtask

### ISSUE THREAD

**Issue by cpfiffer** [TuringLang/Libtask.jl#51]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register

**Comment by cpfiffer** [comment]
Looks like we didn't have a julia compat, I've updated the repo:

@JuliaRegistrator register

**Comment by yebai** [comment]
@JuliaRegistrator register
