### ISSUE TITLE
Improving artefacts uploading process 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#53]
Maybe we can modify the [build](https://github.com/TuringLang/Libtask.jl/blob/master/.github/workflows/BuildDylib.yaml) script of `Libtask`, so that a tag is automatically created if the tag does not exist? This would allow uploading artefacts for new Libtask versions even before a new version is accepted by JuliaRegistry.

**Comment by devmotion** [comment]
IMO the correct approach would be to separate building and releasing the binaries into a separate package (and finally to Yggdrasil at some point), as outlined in https://github.com/TuringLang/Libtask.jl/pull/56#issuecomment-605689423.

**Comment by devmotion** [comment]
BTW I just noticed that the current setup with automatically creating tags implies that only exactly the commit for which the tag was created can be registered in the registry (e.g., if the version number is updated in the PR, then a tag is created for this commit and it is impossible to use JuliaRegistrator on the master branch or the merge commit afterwards).

**Comment by KDr2** [comment]
Close in favor of #58
