### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mohamed82008** [TuringLang/Libtask.jl#6]
We should probably tag a new release to enable Turing to be used on Julia v0.7.

**Comment by yebai** [comment]
Please go ahead to tag a new release. Note that there is an [issue](https://github.com/JuliaLang/METADATA.jl/pull/17764#issuecomment-419371927) `BinaryProvider` on JuliaCI. However, this might be fixed now. 

Related: https://github.com/TuringLang/Libtask.jl/issues/4

**Comment by mohamed82008** [comment]
I don't think I have commit access to this repo.

**Comment by yebai** [comment]
> I don't think I have commit access to this repo.

Fixed.

**Comment by mohamed82008** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18761
