### ISSUE TITLE
Error building Libtask

### ISSUE THREAD

**Issue by jibaneza** [TuringLang/Libtask.jl#68]
after turing update to v0.12.0 on Windows 10 I get:

   Building Libtask → `C:\Users\**\.julia\packages\Libtask\Q1ugc\deps\build.log`
┌ Error: Error building `Libtask`:
│ ERROR: LoadError: LibraryProduct(nothing, ["libtask_v1_3"], :libtask_v1_3, "Prefix(C:\\Users\\**\\.julia\\packages\\Libtask\\Q1ugc\\deps\\usr)") is not satisfied, cannot generate deps.jl!
│ Stacktrace:
│  [1] error(::String) at .\error.jl:33
│  [2] write_deps_file(::String, ::Array{LibraryProduct,1}; verbose::Bool, isolate::Bool) at C:\Users\**\.julia\packages\BinaryProvider\GeAtj\src\Products.jl:419
│  [3] top-level scope at C:\Users\**\.julia\packages\Libtask\Q1ugc\deps\build.jl:58
│  [4] include(::String) at .\client.jl:439
│  [5] top-level scope at none:5
│ in expression starting at C:\Users\**\.julia\packages\Libtask\Q1ugc\deps\build.jl:58
└ @ Pkg.Operations D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\Pkg\src\Operations.jl:892

**Comment by devmotion** [comment]
I assume it's the same problem as described in https://github.com/TuringLang/Libtask.jl/issues/67. Can you try the solution in https://github.com/TuringLang/Libtask.jl/issues/67#issuecomment-625763327 and check if it fixes the issue for you as well?

**Comment by jibaneza** [comment]
Yes, that did work. I had to ] add BinaryProvider, and then it could build from there. Thank you for the fast answer!

**Comment by devmotion** [comment]
Great that it fixed your problem!
