### ISSUE TITLE
Libtask waits for ever is function body has errors.

### ISSUE THREAD

**Issue by trappmartin** [TuringLang/Libtask.jl#7]
See the following minimal example:

```julia
using Libtask

function f()
    t = 0;
    while true
        t[2] = 0
        produce(t)
    end
end

t = Task(f)
consume(t)
```

**Comment by trappmartin** [comment]
I tried to do that didn’t manage so far. I’ll have another try next week.

**Comment by trappmartin** [comment]
@yebai could you have a look at this? I tried to resolve this issue on the branch `mt/broken_function` but with almost no success so far.

**Comment by yebai** [comment]
There seems to be a bug in function `Base.schedule_and_wait`, which does not throw `Exception` as expected. Here is an MWE

```julia

function f()
           t = 0;
           while true
               t[2] = 0
               produce(t)
           end
end

Base.schedule(Task(f))
Task (failed) @0x0000000113da86d0
MethodError: no method matching setindex!(::Int64, ::Int64, ::Int64)
f() at ./REPL[4]:4

Base.schedule_and_wait(Task(f)) # never returns. 
```

**Comment by mohamed82008** [comment]
`schedule(t)` passes `t` to the scheduler for execution and moves on. It doesn't throw anything:
```julia
julia> f() = error("Ignored error")
f (generic function with 1 method)

julia> g() = (schedule(Task(f)); 1)
g (generic function with 1 method)

julia> g()
1
```
`wait` will dismiss the current task until re`schedule`d or `yieldto` is called. When you do this in the main task, and no other task is going to `schedule` it again, your program will freeze. `schedule_and_wait` just calls `schedule` then `wait` so the freezing effect of `wait` is still there, when called in the main task.

**Comment by yebai** [comment]
Related: https://github.com/TuringLang/Turing.jl/issues/594
