### ISSUE TITLE
Create a Julia implementation of the C task struct 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#90]
It might be possible to create a Julia version of the task struct, based on the memory layout information in #89, then we can further simplify the `getfield/setfield` functions for manipulating the task fields. It might require creating some new bit types (or primitive types) to represent arbitrarily sized memory blocks without clear Julia equivalent type.

**Comment by giordano** [comment]
creating a Julia struct which mimics the layout of `jl_task_t` should help with #85. As annoying as maintaining such a (likely version-dependent) struct is, not having to build an external library just to call into libjulia looks a big win to me.

**Comment by yebai** [comment]
Closed in favour of #93
