### ISSUE TITLE
arm64-apple-darwin21.1.0 support

### ISSUE THREAD

**Issue by enweg** [TuringLang/Libtask.jl#94]
Just tried whether Turing would work in Julia 1.7.0 on a Mac Air M1 and ran into the problem that Libtask was not properly installed. I then tried building libtask as described in the error message and got the error that currently apple arm architectures are not supported. Are there any plans to change this soon? Especially now that Julia 1.7.0 officially supports that architecture.

**Comment by yebai** [comment]
This will be fixed soon by https://github.com/TuringLang/Libtask.jl/pull/93

**Comment by yebai** [comment]
Fixed by https://github.com/TuringLang/Libtask.jl/pull/107
