### ISSUE TITLE
Failing to build Libtask and install Turing

### ISSUE THREAD

**Issue by bpajusco** [TuringLang/Libtask.jl#95]
I'm a total newbie and trying to use Turing for the very first time. In building the package for my M1 Mac the manager fails and complains about issues with Libtask but I can't say I fully understand what's happening here. Here is the full traceback.

(@v1.7) pkg> add Turing
   Resolving package versions...
  No Changes to `~/.julia/environments/v1.7/Project.toml`
  No Changes to `~/.julia/environments/v1.7/Manifest.toml`
Precompiling project...
  ✗ BinaryProvider
  ✗ Libtask
  ✗ ThreadingUtilities
  ✗ SLEEFPirates
  ✗ LoopVectorization
  ✗ RecursiveFactorization
  ✗ NonlinearSolve
  ✗ Bijectors
  ✗ DiffEqBase
  ✗ OrdinaryDiffEq
  ✗ DynamicPPL
  ✗ AdvancedVI
  ✗ GpABC
  ✗ Turing
  80 dependencies successfully precompiled in 51 seconds (174 already precompiled)
  14 dependencies errored. To see a full report either run `import Pkg; Pkg.precompile()` or load the packages

and this is the traceback when I try to build the package

(@v1.7) pkg> build Turing
    Building Libtask → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/83e082fccb4e37d93df6440cdbd41dcbe5e46cb6/build.log`
ERROR: Error building `Libtask`: 
┌ Warning: Platform `arm64-apple-darwin21.1.0` is not an officially supported platform
└ @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:450
ERROR: LoadError: KeyError: key "unknown" not found
Stacktrace:
  [1] getindex
    @ ./dict.jl:481 [inlined]
  [2] parse_dl_name_version
    @ ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:511 [inlined]
  [3] detect_libgfortran_abi(libgfortran_name::String, platform::BinaryProvider.UnknownPlatform) (repeats 2 times)
    @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:555
  [4] detect_libgfortran_abi
    @ ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:584 [inlined]
  [5] detect_compiler_abi()
    @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:667
  [6] top-level scope
    @ ~/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:685
  [7] include(mod::Module, _path::String)
    @ Base ./Base.jl:418
  [8] include(x::String)
    @ BinaryProvider ~/.julia/packages/BinaryProvider/U2dKK/src/BinaryProvider.jl:1
  [9] top-level scope
    @ ~/.julia/packages/BinaryProvider/U2dKK/src/BinaryProvider.jl:12
 [10] include
    @ ./Base.jl:418 [inlined]
 [11] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1318
 [12] top-level scope
    @ none:1
 [13] eval
    @ ./boot.jl:373 [inlined]
 [14] eval(x::Expr)
    @ Base.MainInclude ./client.jl:453
 [15] top-level scope
    @ none:1
in expression starting at /Users/bpajusco/.julia/packages/BinaryProvider/U2dKK/src/PlatformNames.jl:685
in expression starting at /Users/bpajusco/.julia/packages/BinaryProvider/U2dKK/src/BinaryProvider.jl:1
ERROR: LoadError: Failed to precompile BinaryProvider [b99e7846-7c00-51b0-8f62-c81ae34c0232] to /Users/bpajusco/.julia/compiled/v1.7/BinaryProvider/jl_vEZwnJ.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] compilecache(pkg::Base.PkgId, path::String, internal_stderr::IO, internal_stdout::IO, ignore_loaded_modules::Bool)
   @ Base ./loading.jl:1466
 [3] compilecache(pkg::Base.PkgId, path::String)
   @ Base ./loading.jl:1410
 [4] _require(pkg::Base.PkgId)
   @ Base ./loading.jl:1120
 [5] require(uuidkey::Base.PkgId)
   @ Base ./loading.jl:1013
 [6] require(into::Module, mod::Symbol)
   @ Base ./loading.jl:997
 [7] include(fname::String)
   @ Base.MainInclude ./client.jl:451
 [8] top-level scope
   @ none:5
in expression starting at /Users/bpajusco/.julia/packages/Libtask/OtgFl/deps/build.jl:9

**Comment by yebai** [comment]
`Libtask` doesn't support Julia 1.7 yet. See #93 and https://github.com/TuringLang/Libtask.jl/pull/92

**Comment by yebai** [comment]
Dup of https://github.com/TuringLang/Libtask.jl/issues/91

**Comment by bpajusco** [comment]
Pardon my lack of understanding but I don't know how I'm supposed to fix this. I don't understand what 'taped' version means and from #93 I gather that there is no fix for this. Am I right? Does it mean I have to use a previous version of Julia to access Turing? If so, there isn't an ARM build for Julia LTS so what am I to do? Just wait until this is fixed and if so when is this expected to be solved?

**Comment by yebai** [comment]
yes, please use Julia 1.6 for now; we plan to fix the issue for Julia 1.7 soon. The new mechanism will work for ARM as well. If you are using HMC sampling only, Turing will work for Julia 1.7 despite the Libtask issue. You will need to force install Turing in that case.
