### ISSUE TITLE
Seprate code and data in instructions 

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#97]
The current `Instruction` type 

```julia
mutable struct Instruction{F}
    fun::F
    input::Tuple
    output
    tape
end
```

carries both the code (i.e. `fun::F`) and data (i.e. `input` and `output`). If we want to support loops suggested [here](https://github.com/TuringLang/Libtask.jl/issues/96), we likely will need a mechanism to store multiple copies of data in the same instruction. It is because each instruction might run multiple times assuming we copy the control flow IR onto the tape without linearization. Maybe we can turn `input` and `output` into a vector? 

```julia
struct Instruction{F}
    fun::F
    io::Vector{InstructionIO}
    tape
end

struct InstructionIO
    input::Tuple
    output
end
```

**Comment by KDr2** [comment]
Running an instruction multiple times doesn't interfere with data copying I think, so maybe we need not do this?
