### ISSUE TITLE
Allow `TapedFunction` as a special Instruction

### ISSUE THREAD

**Issue by yebai** [TuringLang/Libtask.jl#99]
We currently treat all instructions on a tape as primitive. There are use-cases (see [here](https://github.com/TuringLang/Turing.jl/pull/1744#issuecomment-993659965)) where we need to selectively trace into instructions. One neat way of achieving that is to have a special instruction type that allows us to plug a tape A into another tape B, where tape A is considered as a standard instruction on tape B. This way, we can create a dedicated tape for an instruction that we want to trace into, and use it on another (parent) tape.

**Comment by KDr2** [comment]
Fixed by https://github.com/TuringLang/Libtask.jl/pull/100.

**Comment by KDr2** [comment]
Do we still need this feature?

**Comment by yebai** [comment]
We might still want to selectly convert some function calls into `TapedFunctions`. Let's revisit this later.

**Comment by yebai** [comment]
Probably not necessary after #138
